name: inji-verify build upon a push

on:
  release:
    types: [published]
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - '!release-branch'
      - release*
      - master
      - 1.*
      - develop
      - MOSIP*

jobs:
  build-maven-inji-verify:
    uses: mosip/kattu/.github/workflows/maven-build.yml@master-java21
    with:
      SERVICE_LOCATION: ./
      BUILD_ARTIFACT: inji-verify
    secrets:
      OSSRH_USER: ${{ secrets.OSSRH_USER }}
      OSSRH_SECRET: ${{ secrets.OSSRH_SECRET }}
      OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
      GPG_SECRET: ${{ secrets.GPG_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  build-dockers-inji-verify:
    strategy:
      matrix:
        include:
          - SERVICE_LOCATION: "ui"
            SERVICE_NAME: "inji-verify-ui"
      fail-fast: false
    name: ${{ matrix.SERVICE_NAME }}
    needs: build-maven-inji-verify
    uses: mosip/kattu/.github/workflows/docker-build.yml@master-java21
    with:
      SERVICE_LOCATION: ${{ matrix.SERVICE_LOCATION }}
      SERVICE_NAME: ${{ matrix.SERVICE_NAME }}
    secrets:
      DEV_NAMESPACE_DOCKER_HUB: ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}
      ACTOR_DOCKER_HUB: ${{ secrets.ACTOR_DOCKER_HUB }}
      RELEASE_DOCKER_HUB: ${{ secrets.RELEASE_DOCKER_HUB }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  publish_to_nexus:
      if: "${{ !contains(github.ref, 'master') && github.event_name != 'pull_request' && github.event_name != 'release' && github.event_name != 'prerelease' && github.event_name != 'publish' }}"
      needs: build-dockers-inji-verify
      uses: mosip/kattu/.github/workflows/maven-publish-to-nexus.yml@master-java21
      with:
        SERVICE_LOCATION: ./
      secrets:
        OSSRH_USER: ${{ secrets.OSSRH_USER }}
        OSSRH_SECRET: ${{ secrets.OSSRH_SECRET }}
        OSSRH_URL: ${{ secrets.OSSRH_SNAPSHOT_URL }}
        OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
        GPG_SECRET: ${{ secrets.GPG_SECRET }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  sonar-analysis-inji-verify:
    if: "${{  github.event_name != 'pull_request' }}"
    needs: build-dockers-inji-verify
    uses: mosip/kattu/.github/workflows/npm-sonar-analysis.yml@master-java21
    with:
      SERVICE_LOCATION: ./ui
      SONAR_URL: 'https://sonarcloud.io'
      PROJECT_KEY: 'mosip_inji-verify'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      ORG_KEY: ${{ secrets.ORG_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
